services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    ports:
      - "8222:80"
    environment:
      TZ: Europe/Paris
      DOMAIN: https://<TAILSCALE_FQDN>
      SIGNUPS_ALLOWED: "true"
      INVITATIONS_ALLOWED: "false"
      SHOW_PASSWORD_HINT: "false"
      PASSWORD_HINTS_ALLOWED: "false"
    volumes:
      - ./data:/data
    restart: unless-stopped
