services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    environment:
      TZ: Europe/Paris
      DOMAIN: https://<SUBDOMAIN>.<DOMAIN>
      SIGNUPS_ALLOWED: "true"
      INVITATIONS_ALLOWED: "false"
      SHOW_PASSWORD_HINT: "false"
      PASSWORD_HINTS_ALLOWED: "false"
    volumes:
      - ./data:/data
    restart: unless-stopped

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      TUNNEL_TOKEN: "<TUNNEL_TOKEN>"
    restart: unless-stopped
    depends_on:
      - vaultwarden
