services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    # Pinné à 2.13.0 le 2026-08-06 après mise à jour et vérification (MQTT connecté, démarrage propre, 0 devices pour l'instant)
    image: koenkk/zigbee2mqtt:2.13.0
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
    volumes:
      - ./data:/app/data
    devices:
      - /dev/ttyAMA0:/dev/ttyAMA0
    network_mode: host
